openapi: 3.0.3
info:
  title: Car info
  version: 0.0.1
servers:
- url: /
paths:
  /info:
    get:
      parameters:
      - name: regNum
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    Car:
      required:
      - mark
      - model
      - owner
      - regNum
      type: object
      properties:
        regNum:
          type: string
          example: X123XX150
        mark:
          type: string
          example: Lada
        model:
          type: string
          example: Vesta
        year:
          type: integer
          example: 2002
        owner:
          $ref: '#/components/schemas/People'
      example:
        owner:
          patronymic: patronymic
          surname: surname
          name: name
        regNum: X123XX150
        year: 2002
        model: Vesta
        mark: Lada
    People:
      required:
      - name
      - surname
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
      example:
        patronymic: patronymic
        surname: surname
        name: name
