/*
 * Car info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	swagger "sw/go"
)

func main() {
	log.Printf("Server started")
	router := swagger.NewRouter()
	log.Fatal(http.ListenAndServe(":9001", router))
}
