/*
 * Car info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"fmt"
	"net/http"
)

func InfoGet(w http.ResponseWriter, r *http.Request) {
	cars := getCar()
	regNum := r.FormValue("regNum")
	fmt.Println(regNum)
	car, ok := cars[regNum]
	if ok {
		j, _ := json.Marshal(car)

		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusOK)
		w.Write(j)
	} else {
		w.WriteHeader(http.StatusNotFound)
	}

}
